export const COLOR_GREY = '#2F4553'
export const COLOR_GREY_LIGHT = 'rgb(75, 110, 132)'
export const COLOR_RED = '#FE2247'
export const COLOR_RED_LIGHT = 'rgb(254, 110, 134)'
export const COLOR_GREEN = '#439E42'
export const COLOR_GREEN_LIGHT = 'rgb(105, 194, 103)'
export const COLOR_BLACK = '#2F4553'
export const COLOR_BLACK_LIGHT = 'rgb(75, 110, 132)'

export enum BoardConfigButtonEnum {
  BUTTON = 'button',
  NUMBER = 'number',
}

export type BoardConfigButtonType = {
  label: string | number
  cols: number
  gridArea: string
  color: string
  colorHover: string
  colorBlack: string
  colorBlackHover: string
  type: BoardConfigButtonEnum
}

export type BoardConfigType = {
  row1: BoardConfigButtonType[]
  row2: BoardConfigButtonType[]
  row3: BoardConfigButtonType[]
  row4: BoardConfigButtonType[]
  row5: BoardConfigButtonType[]
}

export const BOARD_CONFIG: BoardConfigType = {
  row1: [
    {
      label: 0,
      color: COLOR_GREEN,
      colorHover: COLOR_GREEN_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number0',
      cols: 1,
    },
    {
      label: 3,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number3',
      cols: 1,
    },
    {
      label: 6,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number6',
      cols: 1,
    },
    {
      label: 9,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number9',
      cols: 1,
    },
    {
      label: 12,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number12',
      cols: 1,
    },
    {
      label: 15,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number15',
      cols: 1,
    },
    {
      label: 18,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number18',
      cols: 1,
    },
    {
      label: 21,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number21',
      cols: 1,
    },
    {
      label: 24,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number24',
      cols: 1,
    },
    {
      label: 27,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number27',
      cols: 1,
    },
    {
      label: 30,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number30',
      cols: 1,
    },
    {
      label: 33,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number33',
      cols: 1,
    },
    {
      label: 36,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number36',
      cols: 1,
    },
    {
      label: '2:1',
      color: '',
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
      gridArea: 'row1',
      cols: 1,
    },
  ],
  row2: [
    {
      label: 0,
      color: COLOR_GREEN,
      colorHover: COLOR_GREEN_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number0',
      cols: 1,
    },
    {
      label: 2,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number2',
      cols: 1,
    },
    {
      label: 5,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number5',
      cols: 1,
    },
    {
      label: 8,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number8',
      cols: 1,
    },
    {
      label: 11,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number11',
      cols: 1,
    },
    {
      label: 14,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number14',
      cols: 1,
    },
    {
      label: 17,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number17',
      cols: 1,
    },
    {
      label: 20,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number20',
      cols: 1,
    },
    {
      label: 23,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number23',
      cols: 1,
    },
    {
      label: 26,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number26',
      cols: 1,
    },
    {
      label: 29,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number29',
      cols: 1,
    },
    {
      label: 32,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number32',
      cols: 1,
    },
    {
      label: 35,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number35',
      cols: 1,
    },
    {
      label: '2:1',
      color: '',
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
      gridArea: 'row2',
      cols: 1,
    },
  ],
  row3: [
    {
      label: 0,
      color: COLOR_GREEN,
      colorHover: COLOR_GREEN_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
      gridArea: 'number0',
      cols: 1,
    },
    {
      label: 1,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number1',
      cols: 1,
    },
    {
      label: 4,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number4',
      cols: 1,
    },
    {
      label: 7,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number7',
      cols: 1,
    },
    {
      label: 10,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number10',
      cols: 1,
    },
    {
      label: 13,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number13',
      cols: 1,
    },
    {
      label: 16,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number16',
      cols: 1,
    },
    {
      label: 19,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number19',
      cols: 1,
    },
    {
      label: 22,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number22',
      cols: 1,
    },
    {
      label: 25,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number25',
      cols: 1,
    },
    {
      label: 28,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number28',
      cols: 1,
    },
    {
      label: 31,
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number31',
      cols: 1,
    },
    {
      label: 34,
      color: COLOR_RED,
      colorHover: COLOR_RED_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.NUMBER,
      gridArea: 'number34',
      cols: 1,
    },
    {
      label: '2:1',
      color: '',
      colorHover: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
      gridArea: 'row3',
      cols: 1,
    },
  ],

  row4: [
    {
      label: '1 to 12',
      cols: 4,
      gridArea: 'range0112',
      color: '',
      colorHover: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: '13 to 24',
      cols: 4,
      gridArea: 'range1324',
      color: '',
      colorHover: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: '25 to 36',
      cols: 4,
      gridArea: 'range2536',
      color: '',
      colorHover: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
  ],
  row5: [
    {
      label: '1 to 18',
      cols: 2,
      gridArea: 'range0118',
      color: '',
      colorHover: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: 'Even',
      cols: 2,
      gridArea: 'parityEven',
      colorHover: '',
      color: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: '',
      cols: 2,
      gridArea: 'colorRed',
      colorHover: COLOR_RED_LIGHT,
      color: COLOR_RED,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: '',
      cols: 2,
      gridArea: 'colorBack',
      color: COLOR_GREY,
      colorHover: COLOR_GREY_LIGHT,
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: 'Odd',
      cols: 2,
      gridArea: 'parityOdd',
      colorHover: '',
      color: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
    {
      label: '19 to 36',
      cols: 2,
      gridArea: 'range1936',
      color: '',
      colorHover: '',
      colorBlack: COLOR_BLACK,
      colorBlackHover: COLOR_BLACK_LIGHT,
      type: BoardConfigButtonEnum.BUTTON,
    },
  ],
}
